apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue-learn
  labels:
    app: hue
    service: learn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hue
      service: learn
  template:
    metadata:
      labels:
        app: hue
        service: learn
    spec:
      containers:
        - name: hue-learner
          image: g1g1/hue-learn:0.3
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          env:
            - name: DISCOVER_QUEUE
              value: dns
            - name: DISCOVER_STORE
              value: dns