apiVersion: v1
kind: Service
metadata:
  name: hue-reminders-external1
  labels:
    app: hue
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    app: hue